[package]
name = "easy_private_voting_contract"
type = "contract"
authors = [ "" ]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.69.1", directory = "noir-projects/aztec-nr/aztec" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.69.1", directory = "noir-projects/aztec-nr/authwit" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.69.1", directory = "noir-projects/aztec-nr/uint-note" }

token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.69.1", directory = "noir-projects/noir-contracts/contracts/token_contract" }