[package]
name = "shared_note"
type = "contract"
authors = [ "" ]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.65.2", directory = "noir-projects/aztec-nr/aztec" }
